# Generated by Django 3.2.25 on 2024-11-15 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20241115_1449'),
        ('investors', '0005_alter_investor_fee_percentage'),
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('bills', models.ManyToManyField(related_name='capital_calls', to='bills.Bill')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='investors.investor')),
            ],
        ),
        migrations.DeleteModel(
            name='CapitalCall',
        ),
    ]
