# Generated by Django 3.2.25 on 2024-11-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='investor',
            name='upfront_fees_paid',
            field=models.BooleanField(default=False),
        ),
    ]
