# Generated by Django 3.2.25 on 2024-11-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_alter_investor_fee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investor',
            name='membership_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='years_paid',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
