# Generated by Django 3.2.25 on 2024-11-16 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0007_auto_20241116_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investment_date', models.DateField()),
                ('investment_type', models.CharField(max_length=50)),
                ('fee_percentage', models.DecimalField(decimal_places=3, default=10.0, max_digits=5)),
                ('years_paid', models.IntegerField(blank=True, default=1)),
                ('upfront_fees_paid', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investors.investor')),
            ],
        ),
    ]
