# Generated by Django 3.2.25 on 2024-11-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
