# Generated by Django 3.2.25 on 2024-11-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_auto_20241117_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='investment_fees_paid',
            new_name='investment_fees_paid_years',
        ),
    ]
