# Generated by Django 3.2.25 on 2024-11-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_rename_investment_fees_paid_investment_investment_fees_paid_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investment_fees_paid_years',
        ),
    ]
