# Generated by Django 3.2.25 on 2024-11-15 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_auto_20241116_0012'),
        ('bills', '0002_auto_20241115_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_bills', to='capital.capital'),
        ),
    ]
