# Generated by Django 3.2.25 on 2024-11-16 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
        ('bills', '0003_bill_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='investment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.investment'),
        ),
    ]
