# Generated by Django 3.2.25 on 2024-11-17 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_auto_20241117_0227'),
        ('bills', '0004_bill_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='investment.investment'),
        ),
    ]
