# Generated by Django 3.2.25 on 2024-11-17 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_remove_investment_investment_fees_paid_years'),
        ('bills', '0005_alter_bill_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='investment.investment'),
        ),
    ]
